stages:
  - deploy
  

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update && apt-get install -y openssh-client ansible
    - eval $(ssh-agent -s)
    - echo "$CI_PRIVATE_KEY" | tr -d '\r' | sed 's/\\n/\n/g' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - ssh-keyscan -H ec2-13-59-214-197.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  script:
    - ssh ubuntu@ec2-13-59-214-197.us-east-2.compute.amazonaws.com "ansible-playbook /etc/ansible/configuration.yaml"
